# Generated by Django 3.0.8 on 2020-11-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
