# Generated by Django 3.0.8 on 2020-11-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0006_auto_20201121_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reply', models.CharField(max_length=400)),
                ('text_reply', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='DEMOAPP.Comment')),
            ],
        ),
    ]
