# Generated by Django 3.0.8 on 2020-11-22 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DEMOAPP', '0008_auto_20201122_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postcomment',
            field=models.ManyToManyField(related_name='bolg_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
