# Generated by Django 3.0.8 on 2020-11-22 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0009_post_postcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postcomment',
        ),
        migrations.AddField(
            model_name='post',
            name='postcomment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
