# Generated by Django 3.0.8 on 2020-11-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0011_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
